### ISSUE TITLE
Exploration with Eclipse Platform

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#12]
Post supporting materials for Eclipse here.

**Comment by effat** [comment]
More clipboard for Eclipse can be helpful
http://moreclipboard.sourceforge.net/

**Comment by effat** [comment]
Two more resources:
https://github.com/eclipse/swtbot/blob/master/org.eclipse.swt.examples/src/org/eclipse/swt/examples/clipboard/ClipboardExample.java

**Comment by effat** [comment]
https://github.com/google/windowtester/blob/master/com.windowtester_test/src-example/org/eclipse/swt/examples/clipboard/ClipboardExample.java

**Comment by reachspirit** [comment]
Lucidchart software, an extension to get system wide copying and pasting. The software is browser based and support copying and pasting of both images and various formats. It also provide a context menu:

https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by reachspirit** [comment]
W3C provides a detailed tutorial for learning Clipboard API in Javascript and HTML. We can build our application on this API.

https://w3c.github.io/clipboard-apis/

Also, the source code is public on github.

https://github.com/w3c/clipboard-apis/
