### ISSUE TITLE
Exploration with Atom Platform

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#14]
Post supporting materials for Atom here.

**Comment by arjunmadan** [comment]
clipboard-plus:
- Allows storing multiple items.
- cmd shift v displays a menu with items copied and allows pasting.
- needs keyboard bindings to work.

More info:
https://atom.io/packages/clipboard-plus

**Comment by arjunmadan** [comment]
textmate-clipboard:
- Stores multiple items.
- No gui. Use different commands to access previous/next item.
- No manual keybindings required.

More info:
https://atom.io/packages/textmate-clipboard

**Comment by arjunmadan** [comment]
clipboard-history
- Similar to clipboard-plus
- Shows time when copied
- Shows minimal context

More info:
https://atom.io/packages/clipboard-history

**Comment by arjunmadan** [comment]
Some docs with examples on building packages for Atom: https://atom.io/docs/latest/
