### ISSUE TITLE
3 Features to be implemented

### ISSUE THREAD

**Issue by effat** [cleebp/csc-510-group-g#17]

**Comment by effat** [comment]
Base -- Clipboard Plus of Atom
1. Add command features like Textmate.
2. Display panel feature.
3. Clipboard history-- search, hover, time, clear, sticky notes.

**Comment by effat** [comment]
![pic](https://cloud.githubusercontent.com/assets/1575219/12959575/0a1e3266-d005-11e5-8fa5-7104b5fca4bc.jpg)

**Comment by cleebp** [comment]
![img_4302](https://cloud.githubusercontent.com/assets/3922117/12960357/da308c62-d008-11e5-887f-f12847601a54.JPG)
