### ISSUE TITLE
Howto: Eclipse Plug-In Development

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#2]
This issue is meant to be a place for information on how to actually write a plug-in for Eclipse.

To start with I have found a link that goes over generally how to begin development on plug-ins, and importantly how to setup your workspace: http://agile.csc.ncsu.edu/SEMaterials/tutorials/plugin_dev/

**Comment by cleebp** [comment]
Here are some more links I found, it seems like most tutorials and guides were written back in 2002-2003 so I am trying to only choose from the more recent ones.

IBM Plug-In Basics (2008): http://www.ibm.com/developerworks/library/os-eclipse-plugindev1/index.html
O'Reilly Intro (2005): http://www.onjava.com/pub/a/onjava/2005/02/09/eclipse.html

**Comment by cleebp** [comment]
Also a note on which version of Eclipse to download, there is a bundled version of Eclipse called, "Eclipse IDE for Eclipse Committers" and it has a whole set of tools already loaded into it that would make our lives easier. For example it has Git integration and something called the PDE which is the Plug-in Development Environment. Here is a link to that specific bundled version of Eclipse (not that the download links are on the right, not the big button at the top): http://www.eclipse.org/downloads/packages/eclipse-ide-eclipse-committers-451/mars1

Eclipse has a good document (but old) on using the PDE to develop plug-ins here: http://www.eclipse.org/articles/Article-PDE-does-plugins/PDE-intro.html

**Comment by arjunmadan** [comment]
I just discovered that when you open this version of Eclipse, there's a tutorial on how to build an Eclipse plugin. Going to be working on that in a bit, and I'll post an update when I'm done.

UPDATE: It takes about half an hour to get a basic hello world extension running. It's pretty much the same set of steps from Eclipse document on using the PDE. Also if you're using Eclipse Neon (the latest version), the documentation has an error. "org.eclipse.ui.actionSets" is deprecated and is now "org.eclipse.ui.command".
