### ISSUE TITLE
A tutorial on creating the first Atom plugin

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#23]
This may help you understand how a plugin works in Atom and figure out the function of each part of the code.

http://blog.fxndev.com/create-your-first-atom-package-in-js/

**Comment by cleebp** [comment]
Thanks this is super helpful!

**Comment by cleebp** [comment]
Also Chapter 3 of the Atom Flight Manual is the official introduction to "hacking" atom, its a good overview:

https://atom.io/docs/v1.5.3/hacking-atom-tools-of-the-trade
