### ISSUE TITLE
Debugging/Testing Clipit-cmd

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#24]
Bulk development on clipit-cmd is done, this issue is a placeholder for my debugging/testing of the plug-ing.

**Comment by cleebp** [comment]
Turns out your tabbing in Coffee Script is incredibly critical, spent a day of debugging only to find that I had a block incorrectly tabbed in my main lib file...

**Comment by arjunmadan** [comment]
Question: Does the Clipit read from the system clipboard or from a local Atom clipboard?

**Comment by arjunmadan** [comment]
Okay, nvm. I just tried it with Atom, and found out it stores the last copied item on the system clipboard.

**Comment by cleebp** [comment]
Sorry for late response, this is how it works in the code:

"atom.clipboard.write element" where element is "selectedText = @editor.getSelectedText()", so it is sort of making its own copy functionality, yet since that functionality is through the same keys as system copy, both its wrapper runs and the system copy runs.

At least I think thats how it all works...

**Comment by cleebp** [comment]
Basic functionality is now implemented and working as intended for Clipit-cmd
