### ISSUE TITLE
Final Demo

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#26]
Right now we are scheduled to demo with Dr. Menzies on Thurs March 3rd at 4pm, and also with Shaown on Wed. March 2nd at 3:30pm [here is the link for sign-ups](https://docs.google.com/spreadsheets/d/11IO6URv5Tq4VlEvlAFC8sa44OCtjwu_rksQoAyeQT8s/edit#gid=0).

We will find out if we need both or just one and then cancel or what not...

**Comment by cleebp** [comment]
Also we can use this issue to post stuff about screen capture resources or what not, if we decide to do the video demo route.

**Comment by cleebp** [comment]
Here is a link to the screencap tool that Atom packages use to create those nice Gifs of the packages in use. Of course our demo might still use videos or some such, but it would probably be nice if we added .gifs of each of the packages running to their respective readme.md's.

I will try it out with mine and report at the meeting my thoughts on the tool.

Link to the tool: http://www.cockos.com/licecap/

**Comment by arjunmadan** [comment]
I removed us from the Wed. March 2nd slot with Shaown, since we have to show our work only once.

**Comment by cleebp** [comment]
Our demo time is now 3:30pm with Shaown, not sure where exactly though...

**Comment by cleebp** [comment]
Here is a tutorial on how to make an envelope

https://www.youtube.com/watch?v=knwh8ODWqKE

**Comment by cleebp** [comment]
Just emailed Shaown and he said that the meeting will take place in the TA office, which is in EB2 on the first floor in 1229B.

**Comment by arjunmadan** [comment]
Where is everyone?!

**Comment by arjunmadan** [comment]
SUCCESS.

**Comment by cleebp** [comment]
Go team!
