### ISSUE TITLE
Mar 2nd Meeting Notes

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#37]
Room 3314.

**Comment by trueblue2704** [comment]
Room 3314

**Comment by cleebp** [comment]
Will discuss demos and such.

**Comment by arjunmadan** [comment]
Before I forget: Need to merge the telemetry branch with master. We can go over this in the meeting and get it done once we've verified everything works as expected.

**Comment by arjunmadan** [comment]
Will probably be 10-15 minutes late today.
