### ISSUE TITLE
Problem with sorting array of objects by properties

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#39]
I have a problem with sorting copied items. Since @history is an array of object and I put count, source  as properties of the object of each copied item, I need to sort an array of objects by their properties. According to javascript, a sort method is provided to array, so what I need to do is like this:

```
history.sort(function(a, b) {
    return a.count - b.count;
});
```

translated to coffeescript, we get:

```
@history.sort (a, b) ->
    a.count - b.count
```

Yet, it showed that a is not defined. I'm not sure whether there are any syntax errors. Any suggestions?

**Comment by effat** [comment]
You can have qsort.
https://atom.io/packages/todo-show

**Comment by reachspirit** [comment]
Thanks for the suggestion. I implemented them with some C style functions. They now works.
