### ISSUE TITLE
DEMO TIME SWITCH

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#43]
Hey guys, Dr. Menzies had something come up during our slot for the demo, so he moved us to 3pm on Thursday with Shaown, can everyone make this time?

I know I can but if someone else can't they should speak up with a time that does work thats still open.

xD

**Comment by arjunmadan** [comment]
I just checked the calendar and it looks like the same slot (4pm on Thursday) is available with Shaown. We could always switch to that. 3pm works for me though.

**Comment by effat** [comment]
I have a class on Thursday at Rick's Hall which ends at 2:45 pm but it
takes some time to take wolfline bus and come to EB2. Can we choose the
next slot? Shawon Thursday 3:30-4 pm? If anybody has any conflict with
3:30-4pm, I can leave my class 10-15 min earlier on Thursday and catch the
3 pm slot.

Hey guys, Dr. Menzies had something come up during our slot for the demo,
so he moved us to 3pm on Thursday with Shaown, can everyone make this time?

I know I can but if someone else can't they should speak up with a time
that does work thats still open.

xD

—
Reply to this email directly or view it on GitHub
https://github.com/cleebp/csc-510-group-g/issues/43.

**Comment by reachspirit** [comment]
Thursday afternoon works for me.

**Comment by cleebp** [comment]
Alright, I'll post on Piazza that we could do any of the other times Thursday afternoon, unfortunately they are all booked.

In case we can't get Thursday afternoon the only other time I know I could make is Wednesday afternoon with Shaown, I guess we could meet with him right after our group meeting?

**Comment by cleebp** [comment]
Our demo time is now 3:30pm with Shaown, will close this thread now.
