### ISSUE TITLE
Clipit-panel additions

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#45]
Hey all,

I'm fiddling with Effat's clipit-panel today and just wanted to log what I'm trying out, if we don't like the changes we can always revert my changes, just thought I'd try to make the interaction a little more seamless!

I'll just post on this issue what I'm trying out...
1. I have made it so that when you copy an item it immediately shows up on the panel, rather than showing up only after hitting the paste command (note for items copied outside of atom they will only show up on the panel after you paste them into atom)

**Comment by cleebp** [comment]
1. Working on making the paste command also just paste the most recent item into the editor (work in progress, harder than it should be)
2. Might look at fiddling with the panel .css

**Comment by arjunmadan** [comment]
Okay, I'll integrate telemetry once you're done. I can probably do it before, but should probably try and avoid those pesky merge conflicts if possible. xD

**Comment by cleebp** [comment]
Sounds good, anything else you think I should look at tweaking for the panel's features?

**Comment by cleebp** [comment]
> 1. Working on making the paste command also just paste the most recent item into the editor (work in progress, harder than it should be)

This is now implemented in my most recent commit, new goal:
- Fix behavior after clicking an item in the panel having to "reset" the panel back to the view

**Comment by cleebp** [comment]
> Fix behavior after clicking an item in the panel having to "reset" the panel back to the view

Fixed, took awhile to figure out how to do this haha.

Probably taking a break for now, I think the panel is in a good place, I wish I understood the way it displays better and how panels work to make it the full height of the panel, which would help with scrolling through items. But I think its definitely demo-able now!

**Comment by cleebp** [comment]
Gonna close this issue since we are theoretically done editing clipit-panel before the demo.
