### ISSUE TITLE
Feb1 report reorganization

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#5]
I think we should consider reorganizing section 2 (Project Goals) and 4 (Copy and Paste in Practice), so that the different ideas we had for the clipboard manager come after section 4, which builds up to the need for one, and how it could help programmers.

What do you all think about this?

**Comment by cleebp** [comment]
I definitely agree, having our project goals towards the end might be the best idea because like you said then our whole report sort of builds the argument for our project.
