### ISSUE TITLE
Project Presentation Slot on April

### ISSUE THREAD

**Issue by effat** [cleebp/csc-510-group-g#52]
What will be our presentation slot? It will be convenient for me other than 4/5, as I have a midterm on that day.

**Comment by effat** [comment]
Available slots : https://goo.gl/OAOZj2

**Comment by arjunmadan** [comment]
I'm alright with anything, have no preference really.

**Comment by arjunmadan** [comment]
Maybe 7th (Thursday) would be a good option since we could use the Wednesday meeting to prepare/do a dry run of the presentation?

**Comment by cleebp** [comment]
Hi sorry for late response was traveling but am back on my laptop now - Thursday the 7th works for me! Maybe we should do the first slot so we can just get it over with?

**Comment by cleebp** [comment]
I have tentatively put us down for slot 1 on the 7th, we can change this of course I just wanted to get us down on that day at least in case other groups start to fill it out.
