### ISSUE TITLE
Meeting Mar 9th

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#54]
Sorry for the late notice, but is it possible to meet at 4pm instead of the usual 2pm tomorrow? I have some work I have to get done in the afternoon.

**Comment by arjunmadan** [comment]
Okay, never mind. Managed to shift stuff around and should be able to make it by 2-2:30.

**Comment by cleebp** [comment]
So I think the room booking site has been offline all day, and all of the normal rooms we grab are full except 3312.

I'm currently in another group study thingy in Hunt but will swing by for a little bit if we are still having the meeting :D

**Comment by reachspirit** [comment]
that's fine with me. I'll be there in a couple of minutes

**Comment by arjunmadan** [comment]
I think we should meet to discuss the experiment so that we can have it
ready by next week to test on people. 😏

I just reached the library. We could meet at 3312 whenever everyone gets
here.

**Comment by arjunmadan** [comment]
We managed to get 3218.

**Comment by arjunmadan** [comment]
- Pre survey (google forms)
- Prep
- Experiment (Telem + observations + check list)
- Post survey (google forms)
