### ISSUE TITLE
Meeting Mar. 30th

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#63]
Room 3314

**Comment by reachspirit** [comment]
Won't come for the meeting. I'm having a stomachache. I've updated the report with a template structure. I'll be watching any posts on the meeting.

**Comment by cleebp** [comment]
Sounds good!

**Comment by arjunmadan** [comment]
Outline of paper:
- Abstract (Effat)
- Introduction (Effat)
- Synopsis (Arjun)
  - January updates
  - Overview of features
    - Panel
    - Order
    - Command
- Experiment (Arjun)
  - Design/methodologies
  - Participants
  - Pre survey
- Results (Ran)
  - Discrete results
  - Compare results
  - Tables/graphs
- Discussion (Brian)
  - Post survey
  - Best feature
  - Future work 
    - each feature improvements
- Conclusion (Brian)
- References
- Appendix

**Comment by cleebp** [comment]
Now till Sunday:
- Work on paper
- Have full draft finished

Sunday:
- Edit paper
- Outline presentation

Sunday to Wednesday:
- Work on presentation

Wednesday:
- Edit presentation

Thursday: 
- Present
