### ISSUE TITLE
Report Structure

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#67]
Have this all fleshed out on sharelatex, will post details here.

**Comment by arjunmadan** [comment]
Outline of paper:
- Abstract (Effat)
- Introduction (Effat)
- Synopsis (Arjun)
  - January updates
  - Overview of features
    - Panel
    - Order
    - Command
- Experiment (Arjun)
  - Design/methodologies
  - Participants
  - Pre survey
- Results (Ran)
  - Discrete results
  - Compare results
  - Tables/graphs
- Discussion (Brian)
  - Post survey
  - Best feature
  - Future work 
    - each feature improvements
- Conclusion (Brian)
- References
- Appendix

**Comment by cleebp** [comment]
Hey Ran since you are not in the meeting right now I'll just leave some notes here on the section you'll be writing...

So we gave you Results, and like the outline above shows (and the name says) this is where we will actually talk about the data from our experiments (by discrete results we just mean numeric results, see the "experimental data" excel sheet). Also compare results here and try to find interesting correlations (i.e. it took people ~4 tasks to learn the feature then all of their speeds increased). Finally make sure to include relevant tables and graphs from our data and reference them in your discussion.

Also just as a reminder the data is all in the "experimental data" google sheet on drive, there are 2 sheets and the second sheet is actually where the interesting data is because it shows times per task per feature.

Finally one last note is that the person I had for control/normal definitely tried way too hard to finish quickly so her data might throw some stuff off.

Also no need to specifically call out a best feature in your results section, as the discussion section will focus more on which feature was the best, etc.

Hope this helps!

**Comment by reachspirit** [comment]
Good job! Thanks for the brief.

**Comment by cleebp** [comment]
Hey Arjun for the participants subsection it will probably be good to reference the demographics of the actual participants we got (through the pre-survey responses) so I trimmed (read; deleted) all of the responses we got that we didn't actually get data for, hope this helps!

**Comment by reachspirit** [comment]
Finished my part of the report. Seems that the report is done. Yeah!

**Comment by cleebp** [comment]
I'm going to go ahead and close this issue now that the whole report is drafted, and open up a new issue to talk specifically about edits if people come across anything big that needs to be changed!
