### ISSUE TITLE
Having problem with telemetry and clipit-cmd

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#69]
While doing experiments with a windows machine, I found that the telemetry doesn't work in windows. The package clipit-cmd works in windows, but there seems to be a problem with 'ctr-shift-j'. I need help with setting up the experiment!

**Comment by arjunmadan** [comment]
What happens with the telemetry? What error do you get?

**Comment by reachspirit** [comment]
I couldn't find the output file. How do you terminate the script?

**Comment by arjunmadan** [comment]
You should just be able to hit ctrl c in the terminal to terminate the
process. The output file should be in the same directory and named whatever
you passed in as a command line argument.

**Comment by reachspirit** [comment]
Yes, I did ctrl c to terminate it and got nothing in the local directory.

**Comment by reachspirit** [comment]
I tried again and it's working this time

**Comment by reachspirit** [comment]
Thanks for the timely help.

**Comment by arjunmadan** [comment]
Did you get clipit-cmd working?

**Comment by reachspirit** [comment]
When I hit 'ctrl-shift-k', it just delete the previous line and nothing is pasted.

**Comment by cleebp** [comment]
Hey I'm travelling right now but the just hitting ctrl shoft j or k should only change the index not actually paste anything - ctrl v will paste from current index.

**Comment by reachspirit** [comment]
But why it deletes the previous line? Is that what you get while testing?

**Comment by cleebp** [comment]
No I have never seen that behavior, perhaps the previous line is still highlighted when you hit a command? Not sure iv never tried it like that.

**Comment by cleebp** [comment]
Did Effat have any problems running clipit-cmd on windows?

**Comment by reachspirit** [comment]
Everything is fine, except the 'ctrl-shift-k' in clipit-cmd. Although I have correct the bug in clipit-order, I would like to explain it again in case of any problem. If you get the '@history undifined' error, just comment 'if state' and '@history=state.data' in clipboard.coffee in lib. That should work.
