### ISSUE TITLE
Multi-item clipboard

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#7]
Find/develop a clipboard manager that has support for multiple items.

**Comment by cleebp** [comment]
Here is a bare bones clipboard manager for sublime that is basically just a history of your copies from within sublime itself:

Github = https://github.com/kemayo/sublime-text-2-clipboard-history
Package = https://packagecontrol.io/packages/Clipboard%20History

**Comment by reachspirit** [comment]
Here are some other great clipboards written in javascript:

https://github.com/zenorocha/clipboard.js/

https://github.com/zeroclipboard/zeroclipboard

The cool thing here is that they provide functions in visualization, so that would be a great help for display option and intelligent context ordering.

**Comment by cleebp** [comment]
Here is another seemingly larger clipboard manager:

Github = https://github.com/colinta/SublimeClipboardManager
Package = https://packagecontrol.io/packages/Clipboard%20Manager

**Comment by cleebp** [comment]
And here is the last big sublime clipboard manager I could find, well featured:

Github = https://github.com/Jimbly/SublimeClipboardHistory
Package = https://packagecontrol.io/packages/Jimbly's%20Clipboard%20History

**Comment by arjunmadan** [comment]
Some info on having  GUI:
https://www.reddit.com/r/SublimeText/comments/1tyhgf/sublime_text_plugin_with_custom_ui_elements/

**Comment by arjunmadan** [comment]
Tutorial for building a sublime plugin from scratch:
http://code.tutsplus.com/tutorials/how-to-create-a-sublime-text-2-plugin--net-22685

**Comment by arjunmadan** [comment]
Atom (https://atom.io) might be the way to go, to overcome some GUI limitations with the Sublime API.

https://atom.io/docs/api/v1.4.3/Panel is something we could use.

**Comment by effat** [comment]
Atom --Clipboard Plus  for our base of project.
