### ISSUE TITLE
pyobjc on mac

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#72]
halp

**Comment by arjunmadan** [comment]
If you can't get it to work you can try - http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by cleebp** [comment]
Looks like some stuff is really bonkers in my system, pip won't work but the solution online is to use home-brew to install python, turns out my home-brew is broken too - weird stuff

**Comment by arjunmadan** [comment]
Oh, that's weird. That makes sense though. Because I used homebrew to install Python. Didn't realize it actually made a difference though. Apple :confounded:

**Comment by cleebp** [comment]
It looks like a lot of these problems are common with the El Capitan update which changed a lot of permissions and such, still digging

**Comment by arjunmadan** [comment]
You could try manually installing it. 

https://pythonhosted.org/pyobjc/install.html

It seems like you just have to run a bunch of setup.py files.

**Comment by arjunmadan** [comment]
Although they might throw the same errors at you. :unamused:

**Comment by cleebp** [comment]
I was able to get virtualenv installed through easy_install and am going to try to get that to work for this, which version of python are you using?

**Comment by arjunmadan** [comment]
2.7 for sure. Not sure about the minor version, but I don't think there's much difference between them in terms of what we're going to be needing. I'm at work now so don't have access to my computer.

**Comment by cleebp** [comment]
So after activating the virtualenv with 2.7 I'm getting literally all of the same errors >.<

**Comment by cleebp** [comment]
Idea: I let them work through the tasks and have a stopwatch with me, record the start stop and total times of each task manually...

**Comment by arjunmadan** [comment]
It might work if you can manage to fix homebrew, and install Python through that.

If you can't/don't have time, using a stopwatch should be fine. You only need to log copies though (pastes are done through atom, except when there is no plugin being used).

**Comment by cleebp** [comment]
Alright sounds good, I'll keep trying to get it to work but will fall back on that as a last resort.
