### ISSUE TITLE
Report Edits

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#78]
Hey guys, as I said in the other issue now that the report is in a finished draft state, we can use this issue to talk about major changes if they come up! 

To start, I just went through and did a bunch of edits to the introduction/abstract, working on the grammar and also embellishing a lot on the lists and breaking them into paragraph form, gonna walk through the rest of the sections in a bit.

**Comment by arjunmadan** [comment]
Made a couple of changes as well - mostly just fixing typos, and working on the grammar.

**Comment by cleebp** [comment]
The more I think about the appendix the more I think we could just site the webpage for our tasks and not worry about it?

**Comment by cleebp** [comment]
So to experiment I commented out the appendix header, cited the tasks.md page and then went through the report and referenced it whenever we made direct reference to the task discriptions/etc, and I think it looks pretty good. 

It also puts us pretty much exactly 6 full pages so thats pretty cool.

**Comment by cleebp** [comment]
Uploaded newest version of the paper to the hub of git then put the shortened url on the submission page!

**Comment by cleebp** [comment]
Going to close this issue since our report is theoretically done!
