### ISSUE TITLE
Presentation Content

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#79]
Since our other issue #75 deals with presentation details (time of presentation, total talking time, etc.) I thought I'd make a new issue specifically on filling out the content of the slides so we can close it once its all drafted.

I'll be spending today working on slide content and will post here with updates/questions.

**Comment by cleebp** [comment]
Just made a bunch of content additions, drafted out slides 2-7 (introduction stuff up to actual feature discussions), made the example tasks slide (it looks like text is overlaying each other but its on purpose, theres animations so 1 task gets replaced by the other), and did the Future Work slide (again stuff is on top of each other, but the animations make it look good). I also added a questions slide and a funny last slide ^.^

To make this easier I'll post a "ToDo" below here and as we go we can take stuff off of it...

Slides left ToDo:
- Clipit-order
- Clipit-panel
- Clipit-cmd
- Experimental design
- Results
- Best Feature

I'm gonna eat lunch then get back to this and will post updates as I go!

**Comment by cleebp** [comment]
Finished clipit-cmd and best feature!

Slides left ToDo:
- Clipit-order
- Clipit-panel
- Experimental design
- Results

**Comment by cleebp** [comment]
Also looking at the notes on piazza it seems like we should have a slide dedicated towards telemetry talking about what we did etc., probably place this in-between experiment/tasks, or after tasks not sure... I have added a blank slide for it for now.

Slides left to do:
- Clipit-order
- Clipit-panel
- Experimental design
- Telemetry
- Results

**Comment by reachspirit** [comment]
I was trying to write something with clipit-order. The problem is that the gif of clipit-order is different from clipit-cmd, so I can't follow the format of clipit-cmd. Do you think it's okay to vary in formats?

**Comment by effat** [comment]
Hey, I have added contents and figure for clipit-panel.

**Comment by effat** [comment]
Also, I have highlighted some texts of other slides by different colors and italics font for each of our features. Please have a look :)

**Comment by cleebp** [comment]
Awesome looks great!

I'm gonna add the updated pdf version to github and link both that and the report to the submissions page.

**Comment by cleebp** [comment]
Uploaded newest version of powerpoint to the hub of git then put the shortened url on the submission page!

**Comment by cleebp** [comment]
Going to close this issue since we are theoretically ready to present!
