### ISSUE TITLE
Getting gitable running

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#83]
- Get gitable running
- Store data for all groups
- Etc.

**Comment by arjunmadan** [comment]
Some useful stuff we can get from GitHub (overkill):

```
1. Activity
    a. Events
        i. Get public events for users
        ii. Get public events for repositories
    b. Stars
        i. List repositories starred by a user
        ii. List users who star a repository
    c. Watches
        i. List repositories watched by a user
        ii. List users who watch a repository
2. Git Data
    a. Commits
        i. Get a commit
            1) Author (person who wrote the code)
            2) Committer (person who added the code to the repo)
            3) When it was done
            4) Commit message
            5) Parent commit
3. Issues (including pull requests)
    a. List issues for a repository
        i. Labels
            1) Name
        ii. Comments
            1) Body - content
            2) User who wrote this
            3) Time
        iii. Number
        iv. State
            1) Open/Closed
        v. Title
        vi. Body
        vii. Milestone (if assigned)
        viii. Assignee (people actively working on the project)
4. Members
    a. List members of an organization
        i. Roles - admin, member
    b. List public organizations a user belongs to
5. Teams (requires authentication - might not work)
    a. Within an organization
    b. Get list of members
        i. Active/Pending
        ii. Role
6. Repositories
    a. List repositories of a user
        i. Issue count
        ii. Stars, forks, watches count
        iii. Languages used
        iv. URLs for commits, comments, issues, labels, languages.
    b. Contributors
        i. Get contributor, sorted in descending order of contributions
    c. List languages, teams, branches
7. Statistics
    a. Contributor list
        i. Additions, deletions, commit count
    b. Weekly commits
        i. Additions, deletions, commits
8. Users
    a. Single user
        i. Followers (list + count)
        ii. Following (list + count)
        iii. Company
        iv. Organizations
        v. Location
        vi. Email
        vii. Bio
        viii. Stars
        ix. Watches
        x. Repos
```

**Comment by arjunmadan** [comment]
Just tried the magic gitable script, and turns out it isn't as magical as we thought. Breaks on page two of commits. I'm trying to figure out why, and hopefully will have the data up tomorrow!

**Comment by arjunmadan** [comment]
And I figured out what's wrong. Turns out it breaks when there's no user attached to a commit - which is what some of the commits look like because of the whole email issue. The other groups I tested it on had it break on commits at the same state. I just verified it ran successfully with a group where there was no commit like this. Time to figure out a workaround!

**Comment by arjunmadan** [comment]
Okay so turns out the magic scripts are more magical than previously thought! They do EVERYTHING. One thing we'll have to work on is cleaning some of the data because people used different 'names' while committing - the whole different email address issue. I think this has to be done manually. Anyway, I'm adding some of the files the scripts generated, and we have A LOT of data now! And A LOT of the analysis done. 😄

**Comment by arjunmadan** [comment]
Data uploaded. Take a look everyone!

**Comment by cleebp** [comment]
Oh man thats a ton of data, yeah figuring out the dual user thing might have to be done manually or some such but all being said thats a pretty small problem considering all the data we now have haha.

**Comment by reachspirit** [comment]
Hi Arjun, can you take a look at the proposed features and criteria for bad smells in the draft? Is it possible for you to get all the data mentioned in the draft? If no, try to find some other stats to replace those in the draft. Feel free to make some changes to the draft.

**Comment by arjunmadan** [comment]
Is there any specific data that's missing? I think we have everything for the things listed already, but I could be mistaken. I guess one thing I can add is the number of lines added/deleted in a commit.

**Comment by effat** [comment]
assignment data of group-g.csv is not relevant. I guess it is the data of bug ratio file. Should I use the old data? I have old data saved in my PC.

**Comment by arjunmadan** [comment]
Should be fixed now. I forgot to add the new CSV files to the push.
