### ISSUE TITLE
Draft statistics and tasks to care about on bad smells

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#85]
How to define bad smells by combination of small features?

**Comment by arjunmadan** [comment]
One thing I thought we could do is find out who owns what files - ownership can be based on who has contributed the most to a file (number of additions - number of deletions), should be able to query this info and store it.

**Comment by reachspirit** [comment]
## Small Features

Summarize the data;
Cluster the data on time(per week), ownership(per person);
- Issues
  - Issue ID
  - Issue Name
  - Creation Time (time of first event)
  - Action Performed (label/unlabel/milestone/closed, etc)
  - User associated with action
- Milestones
  - Milestone ID
  - Description
  - Creation Time
  - Due Time
  - Closed Time
  - User who created it
- Comments
  - User
  - Issue comment was on
  - Timestamp
  - Text of the comment
- Commits
  - User
  - Timestamp
  - Message 

## High Level Features
1. Progress
   - issues created per week (line chart)
   - issues closed per week (line chart)
   - number of commits per week (line chart)
   - identify the time of each deliverable: wait until the last minute
   
   management patterns: waterfall or dev-op
2. Communication
   - participants per issue (pie chart)
   - comments per issue (pie chart)
   - frequency of participation per person (pie chart)
   
   communication patters: centralized or decentralized
3. Collaboration
   - Per issue assiginees (pie chart)
   - contribution to the project in commits: number of commits; number of lines in all commits.
4. Effectiveness
   - lines changed per commit (mean and variance)
   - repetition of deleted and added files: number of adds/deletes (total/percentage)
   - bug fixing issues (total/percentage)

## Bad smells
- normal distribution (get mean and std deviation for each small feature)
- progress: large variance, wait until the last minute
- communication: insufficient communication(small mean value), One announcer--centralized
- collaboration: lack of information on assignees, One person did all the work
- effectiveness: unnecessary commits. no report on bug fixing

## Early bad smells

**Comment by arjunmadan** [comment]
I've added information regarding number of additions, deletions and changes (additions - deletions) and the data should be available in their respective folders. Let me know if there's anything else you need.
