### ISSUE TITLE
Meeting Apr 27th

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#86]
Well I forgot to reserve a room last week and by now everything is booked for tomorrow because of finals xD

We have a couple options, we could try to just find an open table somewhere in Hunt... Or we could meet in my lab! We have a giant whiteboard and tons of space and chairs and such, it will also be quiet so its a good meeting space.

Let me know what you guys want to do!

**Comment by arjunmadan** [comment]
Your lab is probably a better idea. I bet there are working markers too! 😛

**Comment by reachspirit** [comment]
Hi, I just realised that one of my exam begins at 1pm instead of the normal
4:30. I'm afraid that I can't make it at 2pm. I'll let you know if I finish
it early.

**Comment by cleebp** [comment]
Okay so lets plan on my lab KDL (2nd floor of eb 2 by the elevators).

We could also push the meeting back so that Ran can make it, Im free all day :-)

**Comment by arjunmadan** [comment]
I'm free all day as well, so I don't mind pushing the meeting back.

**Comment by effat** [comment]
Hi, I have my graph theory final tomorrow 8-11 am. It's a tough course, I won't be able to attend today's meeting. I'll look at updates of meeting on github.

**Comment by arjunmadan** [comment]
Okay, so I guess delaying the meeting so that Ran is there as well makes sense then. We could push it to tomorrow, but I'll be at work till around 4:30, so we might have to meet after that.

**Comment by cleebp** [comment]
Lets definitely meet today at like 3:30 then and Ran can show up when he is done. 

We can see how much progress we make and probably meet tomorrow night if needed.

Good luck on your graph theory final!

**Comment by reachspirit** [comment]
Hi, I just got it done. Will be there in 10 minutes

**Comment by cleebp** [comment]
Alright meeting is starting so I'ma write notes here:

Effat if you could also upload your R scripts to the rstuff folder that would be really helpful, you can just add a folder called "scripts" inside rstuff where you drop your code. For example we don't understand your boxplot or what it means?

For features we have organized them into four categories each with their own features.

For our graphs we will create as many as we can for each feature; however, in our report we will only display 4 graphs at a time that have been trimmed to format nicely in the report. When we can include outliers in these display graphs that way we can discuss them. I'm pretty sure we can get R to do this or we can manually trim them and make graphics ourselves.

**Comment by cleebp** [comment]
Also we need 4 barplots for major data summarization comparing data points across groups:
- Barplot of total number of commits per group 
- Barplot of total number of issues per group
- Barplot of total number of comments per group
- Barplot of total number of milestones per group

**Comment by cleebp** [comment]
Also we should anonymizing the group names when we create our graphs as such:
- Group B -> group1
- Group C -> group2
- Group F -> group3
- Group G -> group4
- Group I -> group5
- Group M -> group6

**Comment by cleebp** [comment]
Here are the features we need graphs for (in addition to those 4 barplots mentioned above, and recreation of the current ones with group numbers instead of letters), also note these are all one chart per group:
1. Line chart, issues closed per week (data/dmp/group-x_event.csv, filter the action column by "closed")
2. Line chart, number of commits per week  (data/dmp/group-x_commits.csv. the 2nd column is a timestamp that R should be able to make sense of)
3. Histogram, Comments (participants) per issue  (data/csv/issue_comment, we care about total number of issues with 1 participant, 2 participants, 3, etc.)
4. Pie chart, comments per user (this is already done, we just need to change group x to group 1, etc.)
5. Boxplot of true number of comments per issue (data/csv/issue_numcomments)
6. Per issue assigneed (we have this, we just need to change group letters to numbers)
7. Pie chart of changes per user (data/csv/changes_made)
8. Pie chart of issue creations per user (data/csv/issue_create)
9. Pie chart, Bugratio per group (data/csv/bugratio)
10. Histogram (maybe a boxplot?), total changes per commit (data/csv/changes_per_commit)

**Comment by cleebp** [comment]
It would be helpful Effat if you could get these graphs generated as soon as possible (by tomorrow night?), also having just the graphs as .jpegs is fine, in the documents though could you include other information related to that featuere? Things such as means, standard deviations, etc. would be helpful when we are discussing the related graphs in the report.

**Comment by effat** [comment]
I'll upload the graphs by tomorrow :)

**Comment by effat** [comment]
I have uploaded some graphs. But I have some confusions:
- No of milestone files for group b is needed.

-issue_create : group b and g has 5 users. Should I generate graph with 5 users?

-change_made -- group i has 5 users.
- No 3-- Histogram or boxplot is appropriate for comment per issue? Because some groups have 50~60 issues where users have commented, but the number of users is really low 1~4. I think boxplot is good for it-where we can visualize a range of users commenting on per issue.

**Comment by reachspirit** [comment]
you can make a bar chart instead if you don't like histogram. Box plot is
not very good here.

**Comment by effat** [comment]
OK :) I have made bar charts. Please have a look. Do you have any suggestions for labels of X axis and Y axis?

**Comment by arjunmadan** [comment]
There was a bug with the milestone code which made it stop searching for milestones after the first open milestone was found. I fixed it and re-uploaded the databases and dumps, and csvs with the correct information. If you re-run the scripts on the milestone files, you should get the correct output now. Sorry about that.

Also Effat, could you upload the scripts you're using to generate the graphs on GitHub in a folder inside the rscripts folder?

**Comment by effat** [comment]
I have uploaded R scripts. I have made only 1 R Script for a specific type of graph, and changed input file name each time. 

grA-- pie chart generation script.

For bar chart, I have made a single file containing all groups info. For example grComment.csv contains total number of comments for each group. I gathered them from respective group files.

**Comment by effat** [comment]
Can anyone explain me how I can use the info of .csv file to generate the two line graphs? In data/dmp/group-x_commits.csv, the   2nd row is timestamp, I thought it was the timestamp of commiting. But commit#125 has lower timestamp than commit#1. What does this timestamp correspond to?

Also please explain the data of file data/dmp/group-x_event.csv and how I can use this value to generate # issues closed per week.

**Comment by arjunmadan** [comment]
It's possible its in descending order. So commit 1 is actually the latest one.

**Comment by effat** [comment]
Uploaded commits per week line charts and corresponding R script

**Comment by effat** [comment]
I counted the beginning of 1st week since the time stamp for 1st commit in each group.

**Comment by effat** [comment]
data of file data/dmp/group-x_event.csv  has two timestamps on each row. Which one is the closing timestamp?

**Comment by arjunmadan** [comment]
There is only one timestamp - column 2. The last column is an ID.

**Comment by cleebp** [comment]
Those linecharts look really good!

Going to be working on the report today since I'm moving my roommate tomorrow, going to start with adding all of the graphs as single graphics in chunks to the report and placing the figures in the relevent sections, will post here when I'm done :D

**Comment by cleebp** [comment]
Working on adding all the graphs as single images such that we can refer to the entire concept of a feature as a single figure (i.e. all 6 issue assignments pie charts are in the same image and figure that way Figure 6 is just "Figure 6: Issue Assignments").

I think this makes the most sense from an organizational and space standpoint, otherwise we will have like 70000 figures (lol), but it starts to look weird when the graphs are quite large, for example the barplots or linecharts.

From what I can tell this issue will only occur with "changes_per_commit", "commitPerWeek", and "issueComment".

Any ideas on how to get around this with our column format? We could just make individual figures for each group but that adds 18 figures (eek), for "changes_per_commit" I went ahead and made a full graphic with all 6 to show how it looks so you can check it out in the document.

Thoughts?

**Comment by effat** [comment]
Uploaded graphs of issues closed per week. Note that I have taken the Start Time= Earliest closing time of all issues, End Time=Latest close time among all issues. And I divided (EndTime-Start Time) into weeks. So the number of total weeks varies among groups.

**Comment by effat** [comment]
Also uploaded relevant R script

**Comment by cleebp** [comment]
Okay I have created figures for most of the items which are straight foward and put them in the document, here is a list of the ones I have yet to create figures for (note these are all examples of the types of graphs discussed in my earlier post so I'm holding off on making them till we make a decision):
- issues closed per week (progress)
- number of commits per week (progress)
- participants per issue, "issueComment" (communication)
- \* Total changes per commit, iv made a figure of all these plots together as discussed in the comment above but im not sure its the best way to do it (effectiveness)

I really like the linegraphs for the progress sections so those definitely need to stay, but for participants per issue (issueComment) we could also present this in a boxplot similar to issueNumComment.

Thoughts?

I'm gonna take a break from this stuff till tonight so I can check back and work on figures then. I'll be moving my roommate all day tomorrow but might be able to work on this in the PM and Sunday AM.

**Comment by arjunmadan** [comment]
Is it possible to fit two line charts side by side like we’re doing with the pie charts or do they become too small?
I think changes per commit would look good if it were a box plot.

At work now but I can take a look later in the evening.

**Comment by arjunmadan** [comment]
I've finished section 3 for the figures that were in the report. That leaves the subsections Brian mentioned in his comment above.

The report also doesn't look the greatest because of the whole two column, lots of images thing, but I guess there's no way around that. I'll try and get some more done later tonight.

Effat - could you generate a box plot for the changes per commit, like the one for comments per issue? I think that might better represent the data we have.

**Comment by effat** [comment]
I have uploaded the boxplot for changes per commit. But the boxplot does not look much impressive, Gr-C(or Gr 2) data distribution has wide range of value, so you can see only a dot at 8e+06 level along Y axis for group 2.

**Comment by arjunmadan** [comment]
Yikes! Is it possible to remove outliers and show the boxplot? Or any other suggestions?

**Comment by reachspirit** [comment]
I'll try get early bad smells done tonight. It would be great if any of you can provide me the data on those features, but sorted chronologically. Let's get it done!

**Comment by arjunmadan** [comment]
I think if you use the csv files in the dump, you can sort by the timestamp column in most cases. That might help get some data.

**Comment by cleebp** [comment]
Hey Effat, an idea with that boxplot for changes per commit, would it be possible to remove that single outlier data point from group 2? If we did that then I think our boxplot would be much more reasonable looking.

**Comment by effat** [comment]
Hey,
Sorry for late reply. i have removed 2 outlier points from group 2 and uploaded the boxplot of six groups. I have also made boxplots for each groups individually and uploaded them. Have a look and please tell me for any further modifications. :)

**Comment by cleebp** [comment]
Alright so I just did final run through and edits on the report, it ended up compiling really nicely where our references start at the beginning of a new page so I'm not gonna touch it anymore haha.

Going to close this and the other issue with this comment. GO TEAM!
