### ISSUE TITLE
Meeting May 1

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#88]
Hey guys!

So as we know the report is due tomorrow night presumably at midnight. We are really close, need a couple more figures and a bit more writing but its almost done :-D

Arjun and I are gonna meet in my lab at 1pm to try to work out the rest of the report, if anyone else can make it that would be awesome but its not a necessity if you have other commitments, etc. We will document our progress through this issue.

Oh and my lab is the KDL in EB 2 across from the elevators!

**Comment by reachspirit** [comment]
I need to be there to finish my part with early bad smell detection. So,
see you guys tomorrow.

**Comment by cleebp** [comment]
Heyo so I'm here, if you can't get in the building let me know and I'll come down to let you in :-D

**Comment by cleebp** [comment]
Alright so I just did final run through and edits on the report, it ended up compiling really nicely where our references start at the beginning of a new page so I'm not gonna touch it anymore haha.

Going to close this and the other issue with this comment. GO TEAM!

**Comment by arjunmadan** [comment]
Talking about references, do we reference the data folder from this repository?

**Comment by cleebp** [comment]
you just couldn't let it end could you! ;D

And no I don't think we need to, I did cite the R-project page though haha.

**Comment by arjunmadan** [comment]
😜
